repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    # TODO: activate the remaining checks and commit the large diff later
    -   id: check-added-large-files
    -   id: check-case-conflict
    -   id: check-executables-have-shebangs
    -   id: check-json
    #-   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    # -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    # -   id: trailing-whitespace

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    -   id: flake8
        name: flake8 under python2
        language_version: python2
        exclude: ^(doc/source|capsul)/sphinxext/
    -   id: flake8
        name: flake8 under python3
        language_version: python3
        exclude: ^(doc/source|capsul)/sphinxext/
