sudo: false

matrix:
  include:
    - os: osx
      language: generic
      name: python3.7
    - os: linux
      language: python
      name: python 2.7
      python:
        - 2.7
    - os: linux
      language: python
      name: python 3.7
      python:
        - 3.7

before_install:
    # osx deps
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew unlink python@2; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
    - echo "I am here"
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite freetype; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libpng; fi

install:
    - python --version
    - echo "pip:" $(which pip)
    - pip install numpy "six>=1.13"
    - echo "TRAVIS_OS_NAME:" "$TRAVIS_OS_NAME"
    - echo "TRAVIS_PYTHON_VERSION:" "$TRAVIS_PYTHON_VERSION"
    # - pip install nose
    - git clone https://github.com/populse/soma-base.git /tmp/soma-base
    - python /tmp/soma-base/setup.py install
    #- pip install -U setuptools pip
    - git clone https://github.com/populse/populse_db.git /tmp/populse_db
    - pushd /tmp/populse_db
    - PYTHONPATH="/tmp/populse_db/lib/python${TRAVIS_PYTHON_VERSION}/site-packages:$PYTHONPATH" python /tmp/populse_db/setup.py install
    - popd
    # until we release soma-workflow 3.1
    - git clone https://github.com/neurospin/soma-workflow.git /tmp/soma-workflow
    - pushd /tmp/soma-workflow
    - python /tmp/soma-workflow/setup.py install
    - popd
    - pip install argparse
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install importlib; fi
    #- pip install nose-cov
    - pip install codecov;
    # run code quality checks (skip them on Mac OS because Python 3 is not
    # available there)
    - if [[ $TRAVIS_OS_NAME == linux ]]; then pip install pre-commit; fi
    - if [[ $TRAVIS_OS_NAME == linux ]]; then pre-commit run --all-files; fi
    # to test notebooks
    - pip install jupyter nbconvert
    - if [[ "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then sudo apt-get install -y pandoc graphviz; pip install sphinx sphinx-gallery pandoc nbsphinx "PyQt5<5.13"; fi
    - python -c 'import sys; sys.exit(0 if sys.version_info >= (2, 7) else 1)' && pip install nipype || echo "testing without nipype."
    #- pip install soma-workflow
    - python setup.py install
    - export CAPSUL_SOURCE_DIR=$PWD
    - export SOMABASE_INTERSPHINX_URL=http://brainvisa.info/soma-base/sphinx
    - export SOMAWORKFLOW_INTERSPHINX_URL=http://brainvisa.info/soma-workflow/sphinx
    - export QT_API=pyqt5
    # build doc; set .nojekyll otherwise github.io doesn't copy dirs starting
    # with '_' (such as '_static')
    - if [[  "$TRAVIS_OS_NAME" = "linux" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then cd doc && make html && touch build/html/.nojekyll && cd ..; fi
    - if [[ -n "$GITHUB_ACCESS_TOKEN" ]]; then export PUSH_DOC_TO_GH_PAGES=yes; fi
    # don't stay in source directory to actually use the installed capsul
    - cd ..


script:
    - coverage run -m capsul.test

after_success:
    - codecov

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: doc/build/html
  on:
    branch: master
    condition: $PUSH_DOC_TO_GH_PAGES == yes && $TRAVIS_OS_NAME == linux && $TRAVIS_PYTHON_VERSION == 3.7
