sudo: false

matrix:
  include:
    - os: osx
      language: generic
    - os: linux
      language: python
      python:
        - 2.6
    - os: linux
      language: python
      python:
        - 2.7
    - os: linux
      language: python
      python:
        - 3.5

before_install:
    # osx deps
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall --ignore-dependencies python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install freetype; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite freetype; fi
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libpng; fi

install:
    - pip install numpy six
    # - pip install nose
    - if [ ${TRAVIS_PYTHON_VERSION} == "2.6" ]; then pip install "traits==4.6.0"; else pip install traits ;fi
    - if [ ${TRAVIS_PYTHON_VERSION} == "2.6" ]; then pip install "lark-parser==0.6.7"; fi
    #- svn --non-interactive --username brainvisa --password Soma2009 export  https://bioproj.extra.cea.fr/neurosvn/brainvisa/soma/soma-base/branches/bug_fix /tmp/soma-base
    - git clone https://github.com/populse/soma-base.git /tmp/soma-base
    - python /tmp/soma-base/setup.py install
    # until we release soma-workflow 2.9
    #- git clone https://github.com/neurospin/soma-workflow.git /tmp/soma-workflow
    #- pushd /tmp/soma-workflow
    #- python /tmp/soma-workflow/setup.py install
    #- popd
    - pip install argparse
    - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then pip install importlib; fi
    #- pip install nose-cov
    - pip install codecov;
    # to test notebooks
    - if [ ${TRAVIS_PYTHON_VERSION} != "2.6" ]; then pip install jupyter nbconvert; fi
    - python -c 'import sys; sys.exit(0 if sys.version_info >= (2, 7) else 1)' && pip install nipype || echo "testing without nipype."
    - pip install soma-workflow
    - python setup.py install
    - export CAPSUL_SOURCE_DIR=$PWD
    # don't stay in source directory to actually use the installed capsul
    - cd ..

script:
    - coverage run -m capsul.test.test_capsul

after_success:
    - codecov
