image:
  - Visual Studio 2019

environment:

  matrix:

    - PYTHON: "C:\\Python39"
    - PYTHON: "C:\\Python310"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "pip install pydantic"
  - "pip install numpy"
  - "pip install six>=1.13"
  - "pip install traits"
  - IF "%PYTHON%"=="C:\Python27" pip install subprocess32
  - "pip install python-dateutil"
  - "pip install nipype"
  #- "pip install soma-workflow"
  - "git clone --depth=50 --branch=pydantic_controller https://github.com/populse/soma-base.git C:\\projects\\soma-base"
  - "set MAINDIR=%CD%"
  - "cd C:\\projects\\soma-base"
  - "python setup.py install"
  - "git clone --depth=50 --branch=master https://github.com/populse/soma-workflow.git C:\\projects\\soma-workflow"
  - "cd C:\\projects\\soma-workflow"
  - "python setup.py install"
  #- "git clone --depth=50 --branch=master https://github.com/populse/populse_db.git C:\\projects\\populse_db"
  #- "SET PYTHONPATH=C:\\projects\\capsul\\python;%PYTHONPATH%"
  #- "SET PYTHONPATH=C:\\projects\\soma-base\\python;%PYTHONPATH%"
  #- "SET PYTHONPATH=C:\\projects\\soma-workflow\\python;%PYTHONPATH%"
  #- "SET PYTHONPATH=C:\\projects\\populse_db\\python;%PYTHONPATH%"
  - "chdir /c %MAINDIR%"
  - "python setup.py install"

test_script:
  - "python --version"
  - "python -m capsul.test"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
