image: Ubuntu

build: off

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install git+https://github.com/populse/soma-base.git@pydantic_controller
  - python3 -m pip install git+https://github.com/populse/soma-workflow.git
  - python3 -m pip install git+https://github.com/populse/populse_db.git@3.0
  - python3 -m pip install .

test_script:
  - "python3 --version"
  - echo $PYTHONPATH
  - "python3 -c \"import sys; print(sys.path)\""
  - "python3 -m capsul.test"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
