image: Ubuntu

environment:
  matrix:
    - TOXENV: py39

build: off

install:
  - "export MAINDIR=$PWD"
  - "python -m pip install --upgrade pip"
  - "pip install pydantic"
  - "pip install numpy"
  - "pip install six>=1.13"
  - "pip install traits"
  - "pip install python-dateutil"
  - "pip install nipype"
  - "git clone --depth=50 --branch=pydantic_controller https://github.com/populse/soma-base.git /tmp/soma-base"
  - "cd /tmp/soma-base"
  - "python setup.py install"
  - "git clone --depth=50 --branch=master https://github.com/populse/soma-workflow.git /tmp/soma-workflow"
  - "cd /tmp/soma-workflow"
  - "python setup.py install"
  - "git clone --depth=50 --branch=3.0 https://github.com/populse/populse_db.git /tmp/populse_db"
  - "cd /tmp/populse_db"
  - "python setup.py install"
  - "cd $MAINDIR"
  - "python setup.py install"

test_script:
  - "python --version"
  - echo $PYTHONPATH
  - "python -c \"import sys; print(sys.path)\""
  - "python -m capsul.test"

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
