environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      PYTHON: 3.10

build: off

install:
  - python=$HOME/venv$PYTHON/bin/python
  - $python -m pip install --upgrade pip
  - $python -m pip install git+https://github.com/populse/soma-base.git@pydantic_controller
  - $python -m pip install git+https://github.com/populse/soma-workflow.git
  - $python -m pip install git+https://github.com/populse/populse_db.git@3.0
  - $python -m pip install .

test_script:
  - python=$HOME/venv$PYTHON/bin/python
  - $python --version
  - $python -m pip freeze
  - $python -m capsul.test

notifications:
  - provider: Email
    to:
      - '{{commitAuthorEmail}}'
    on_build_failure: true
    on_build_success: false
    on_build_status_changed: true
