---
name: Codespell

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          skip: icones.py,scikit-learn,bootstrap.css
          ignore_words_list: fo,nd,nin
