# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  doc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: "Install Python dependencies"
        run: |
          pip3 install setuptools
          pip3 install numpy 'six>=1.13' 'argparse' 'traits>=4.0' 'populse-db>=2.2' 'PyYAML' 'PyQt5'  # 'soma-base>=5.1' 'soma-workflow>=3.3'
          # for docs only
          sudo apt-get install -y pandoc graphviz
          pip install sphinx sphinx-gallery pandoc nbsphinx ipykernel
          python -m ipykernel install --user --name python3
          # while soma-base 5.1 is not in pip yet
          pushd ..
          git clone https://github.com/populse/soma-base.git
          cd soma-base
          python setup.py install
          popd
          # while soma-workflow 3.3 is not in pip yet
          pushd ..
          git clone https://github.com/populse/soma-workflow.git
          cd soma-workflow
          python setup.py install
          popd
          # python setup.py install

      - name: "Build Sphinx Doc"
        run: |
          export PYTHONPATH=$PWD
          export CAPSUL_SOURCE_DIR=$PWD
          cd doc
          export SOMABASE_INTERSPHINX_URL=https://populse.github.io/soma-base
          export SOMAWORKFLOW_INTERSPHINX_URL=http://populse.github.io/soma-workflow
          export QT_API=pyqt5
          python -m sphinx -b html source build/html
          touch build/html/.nojekyll
          cd ..

      # 3. Déploiement sur les Github Pages

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages     # <- Branche sur laquelle seront commités les fichiers
          FOLDER: doc/build/html/  # <- Dossier contenant notre documentation générée
