# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test_v3

on:
  push:
    branches: [ "celery_redis" ]
    
  pull_request:
    branches: [ "celery_redis", "pydantic_controller" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/populse/soma-base.git@pydantic_controller
        pip install git+https://github.com/populse/soma-workflow.git
        pip install git+https://github.com/populse/populse_db.git@3.0
        pip install .
    - name: Test
      run: |
        python -m capsul.test
        
